### PR TITLE
Implement Extensions System

### LINKED ISSUE #251: Extension System
### Discussed in https://github.com/vignetteapp/vignette/discussions/216

<div type='discussions-op-text'>

<sup>Originally posted by **sr229** May  9, 2021</sup>
This has been requested by the community; however, this is kinda low priority as we focus most on the core components. The way this works is the following:

- Extensions can expose their settings in `MainMenu`.
- They will be strictly be conformant to the o!f model to properly load. This is considered "bare minimum" for what people requires to make an extension.
- They will be packaged as either a `.dll` or a `.nupkg` which the program can "extract" or "compile" into a DLL, something we can do once we have a better idea with how to dynamically load assemblies.

Anyone can propose a better design here since this is a RFC, we appreciate alternative approaches for this.</div>

### PR DESCRIPTION
**Pull request by LeNitrous**
Base implementation for extensions. Closes #251.

### CODE REVIEW

**Review by sr229 — CHANGES_REQUESTED** [review]
You might wanna document how VFS is used to provide filesystem access to the host in Vignette.

**Comment by LeNitrous** [comment]
VFS is a part of Stride. They have documentations for it on their end.

**Comment by sr229** [comment]
> VFS is a part of Stride. They have documentations for it on their end.

We're not talking about the VFS, we're talking about **how** we use it. Is this still in-line with our spec in #216?

**Comment by LeNitrous** [comment]
For the most part yes specially with handling of the metadata.

However, I've taken a few liberties in the scripting API and loading the entry point script. A minimal working example is basically an ES6 Javascript file with two exports named `activate` and `deactivate` respectively. Additionally, the developer can access the core by importing the `vignette` module.

```js
import { vignette } from "vignette";

export function activate() { }

export function deactivate() { }
```

This PR is only the bare minimum and does not fully implement the specification. Other parts of the API will be added in different PRs at a later time after consideration and discussion.

**Review by sr229 — APPROVED** [review]
We'll do a proper RFC to further standardize this so we don't end up in dev hell. Otherwise, LGTM for a initial build.

**Pull request merged**
